In [9]:
import pandas as pd

df = pd.read_csv("../data/data.csv")

df.head()

,id,slug,title,imgs,brand,category,vendor,used,address,availability,...,discounted_price,specifications,description,delivery_fee,delivery_details,warranty,warranty_type,average_rating,num_ratings,reviews
0,0,https://www.mega.pk/mobiles_products/23522/Not...,Nothing Phone 1 8GB RAM 256GB Storage Non PTA ...,['https://www.mega.pk/items_images/Nothing+Pho...,NaN,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",NaN,...,NaN,"{'RAM': '8GB', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
1,1,https://www.mega.pk/mobiles_products/23458/Opp...,Oppo F21 Pro 8GB Ram 128GB Storage 5G PTA Appr...,['https://www.mega.pk/items_images/Oppo+F21+Pr...,OPPO,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",NaN,...,NaN,"{'RAM': '8gb', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,https://www.mega.pk/mobiles_products/24393/Tec...,Tecno Spark 10,['https://www.mega.pk/items_images/Tecno+Spark...,Tecno,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Coming Soon,...,NaN,"{'RAM': '4GB,8GB', 'Memory quantity': '', 'Int...",NaN,NaN,NaN,1 year,NaN,NaN,NaN,[]
3,3,https://www.mega.pk/mobiles_products/24259/Viv...,Vivo V27 5G,['https://www.mega.pk/items_images/Vivo+V27+5G...,Vivo,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Coming Soon,...,NaN,"{'RAM': '8GB,12GB', 'Memory quantity': '', 'In...",NaN,NaN,NaN,1 year,NaN,NaN,NaN,[]
4,4,https://www.mega.pk/mobiles_products/24204/App...,Apple Iphone 15 Pro Max,['https://www.mega.pk/items_images/Apple+Iphon...,Apple,Mobile,MEGA.PK,0,"Office 11, 12, 14 Basement Ahmed Center, I-8 M...",Coming Soon,...,NaN,"{'RAM': '8GB', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]

In [10]:
df.shape

(1666, 22)

In [11]:
df.columns

Index(['id', 'slug', 'title', 'imgs', 'brand', 'category', 'vendor', 'used',
       'address', 'availability', 'currency', 'original_price',
       'discounted_price', 'specifications', 'description', 'delivery_fee',
       'delivery_details', 'warranty', 'warranty_type', 'average_rating',
       'num_ratings', 'reviews'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1666 entries, 0 to 1665
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1666 non-null   int64
 1   slug              1666 non-null   object
 2   title             1666 non-null   object
 3   imgs              1666 non-null   object
 4   brand             773 non-null    object
 5   category          1666 non-null   object
 6   vendor            1666 non-null   object
 7   used              1666 non-null   int64
 8   address           544 non-null    object
 9   availability      1079 non-null   object
 10  currency          1666 non-null   object
 11  original_price    1649 non-null   float64
 12  discounted_price  739 non-null    float64
 13  specifications    1666 non-null   object
 14  description       299 non-null    object
 15  delivery_fee      107 non-null    float64
 16  delivery_details  0 non-null      float64
 17  warranty          500 non-null    object
 18  warranty_type     389 non-null    object
 19  average_rating    900 non-null    float64
 20  num_ratings       900 non-null    float64
 21  reviews           1666 non-null   object
dtypes: float64(6), int64(2), object(14)
memory usage: 286.5+ KB

In [13]:
df.isnull().sum()

id                     0
slug                   0
title                  0
imgs                   0
brand                893
category               0
vendor                 0
used                   0
address             1122
availability         587
currency               0
original_price        17
discounted_price     927
specifications         0
description         1367
delivery_fee        1559
delivery_details    1666
warranty            1166
warranty_type       1277
average_rating       766
num_ratings          766
reviews                0
dtype: int64

In [14]:
df["search_text"] = (
    df["title"].fillna("") + " " +
    df["brand"].fillna("") + " " +
    df["category"].fillna("") + " " +
    df["specifications"].fillna("") + " " +
    df["description"].fillna("")
)

In [15]:
important_columns = [
    "title",
    "brand",
    "category",
    "specifications",
    "description",
    "average_rating",
    "num_ratings",
    "discounted_price"
]

df[important_columns].head()

,title,brand,category,specifications,description,average_rating,num_ratings,discounted_price
0,Nothing Phone 1 8GB RAM 256GB Storage Non PTA ...,NaN,Mobile,"{'RAM': '8GB', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN
1,Oppo F21 Pro 8GB Ram 128GB Storage 5G PTA Appr...,OPPO,Mobile,"{'RAM': '8gb', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN
2,Tecno Spark 10,Tecno,Mobile,"{'RAM': '4GB,8GB', 'Memory quantity': '', 'Int...",NaN,NaN,NaN,NaN
3,Vivo V27 5G,Vivo,Mobile,"{'RAM': '8GB,12GB', 'Memory quantity': '', 'In...",NaN,NaN,NaN,NaN
4,Apple Iphone 15 Pro Max,Apple,Mobile,"{'RAM': '8GB', 'Memory quantity': '', 'Interna...",NaN,NaN,NaN,NaN

In [16]:
df[important_columns].isnull().sum()

title                  0
brand                893
category               0
specifications         0
description         1367
average_rating       766
num_ratings          766
discounted_price     927
dtype: int64

In [17]:
text_columns = [
    "brand",
    "description",
    "specifications"
]

for col in text_columns:
    df[col] = df[col].fillna("")

In [18]:
df["average_rating"] = df["average_rating"].fillna(0)

df["num_ratings"] = df["num_ratings"].fillna(0)

In [19]:
df["search_text"] = (
    df["title"] + " " +
    df["brand"] + " " +
    df["category"] + " " +
    df["specifications"] + " " +
    df["description"]
)

In [20]:
df["search_text"].head()

0    Nothing Phone 1 8GB RAM 256GB Storage Non PTA ...
1    Oppo F21 Pro 8GB Ram 128GB Storage 5G PTA Appr...
2    Tecno Spark 10  Tecno Mobile {'RAM': '4GB,8GB'...
3    Vivo V27 5G  Vivo Mobile {'RAM': '8GB,12GB', '...
4    Apple Iphone 15 Pro Max  Apple Mobile {'RAM': ...
Name: search_text, dtype: object

In [28]:
import re

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'[^a-z0-9\s]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [29]:
df["clean_search_text"] = df["search_text"].apply(clean_text)

In [30]:
df[
    ["title",
     "clean_search_text"]
].head()

,title,clean_search_text
0,Nothing Phone 1 8GB RAM 256GB Storage Non PTA ...,nothing phone 1 8gb ram 256gb storage non pta ...
1,Oppo F21 Pro 8GB Ram 128GB Storage 5G PTA Appr...,oppo f21 pro 8gb ram 128gb storage 5g pta appr...
2,Tecno Spark 10,tecno spark 10 tecno mobile ram 4gb 8gb memory...
3,Vivo V27 5G,vivo v27 5g vivo mobile ram 8gb 12gb memory qu...
4,Apple Iphone 15 Pro Max,apple iphone 15 pro max apple mobile ram 8gb m...

In [24]:
df.to_csv(
    "../data/clean_products.csv",
    index=False
)

In [25]:
# THEN run these
df.shape

df["clean_search_text"].head(3)

0    nothing phone 1 8gb ram 256gb storage non pta ...
1    oppo f21 pro 8gb ram 128gb storage 5g pta appr...
2    tecno spark 10 tecno mobile ram 4gb 8gb memory...
Name: clean_search_text, dtype: object

In [27]:
print(df.shape)

(1666, 24)